-- Migration file: Create Pages table for dynamic static content
-- This script creates the `public.pages` table to store HTML/Markdown content for 'Home', 'Tentang Kami', etc.

CREATE TABLE IF NOT EXISTS public.pages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE,       -- e.g. 'home', 'tentang-kami', 'struktur-organisasi'
    title TEXT NOT NULL,             -- e.g. 'Beranda', 'Tentang Kami', 'Struktur Organisasi'
    content TEXT,                    -- The HTML/Markdown content
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.pages ENABLE ROW LEVEL SECURITY;

-- Policies
-- 1. Anyone can view pages
CREATE POLICY "Pages are viewable by everyone." 
  ON public.pages FOR SELECT USING (true);

-- 2. Only Superadmins can insert pages
CREATE POLICY "Superadmins can insert pages." 
  ON public.pages FOR INSERT WITH CHECK (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'superadmin' AND status = 'approved')
  );

-- 3. Only Superadmins can update pages
CREATE POLICY "Superadmins can update pages." 
  ON public.pages FOR UPDATE USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'superadmin' AND status = 'approved')
  );

-- 4. Only Superadmins can delete pages
CREATE POLICY "Superadmins can delete pages." 
  ON public.pages FOR DELETE USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'superadmin' AND status = 'approved')
  );

-- Insert Default Data
INSERT INTO public.pages (slug, title, content) VALUES
('home', 'Beranda', '<h1>Selamat Datang di Pusat Informasi</h1><p>Ini adalah halaman beranda.</p>'),
('tentang-kami', 'Tentang Kami', '<h1>Tentang Kami</h1><p>Informasi tentang kami.</p>'),
('struktur-organisasi', 'Struktur Organisasi', '<h1>Struktur Organisasi</h1><p>Bagan struktur organisasi.</p>')
ON CONFLICT (slug) DO NOTHING;
